### ISSUE TITLE
Wishing well down?

### ISSUE THREAD

**Issue by ChocoChopin** [JonAbrams/retropatcher#14]
Seems the link for the wishing well doc is down. I can't seem to find any alternatives for requests. Are those just no longer being taken?

**Comment by JonAbrams** [comment]
Not really, no. Sorry!

**Comment by ChocoChopin** [comment]
Understood. Thanks for all of your hard work--your tool remains an invaluable resource, because god knows how long it's going to take Analogue to enable filters for openFPGA.

**Comment by ChocoChopin** [comment]
Understood. Thanks for all of your hard work--your tool remains an invaluable resource, because god knows how long it's going to take Analogue to enable filters for openFPGA.

**Comment by JoseJX** [comment]
I'm (@josejx) happy to take requests over at my github, if you'd like to make requests there.
