### ISSUE TITLE
Pokemon - Blue Version (USA, Europe) (SGB Enhanced)

### ISSUE THREAD

**Issue by phamtq** [JonAbrams/retropatcher#2]
Unable to patch file despite it being available. The page shows the correct MD5 and running md5sum from the Linux command line also shows 50927e843568814f7ed45ec4f944bd8b.

**Comment by JonAbrams** [comment]
Thanks for reporting. I've uploaded the missing patches for Pokemon Red/Blue. Also added the colorization patches. Thanks to @BestPig for the patches!
