### ISSUE TITLE
Some ROMs aren't showing up in the Retro Patcher

### ISSUE THREAD

**Issue by JoseJX** [JonAbrams/retropatcher#3]
BestPig's patches for the European versions of Oracle of Ages and Oracle of Seasons aren't showing up in the patching tool. I haven't tested to see if any others are missing.

Thanks!

**Comment by JonAbrams** [comment]
Is there another page other than [this one](https://gist.github.com/BestPig/528fb9a19cbb638fac1278a641041881)? I don't see the Oracle games there.

**Comment by JoseJX** [comment]
I pinged BestPig, he forgot to add them there, but they were on Strt-Slct. Sorry for the noise!
