### ISSUE TITLE
Patches refresh disabled?

### ISSUE THREAD

**Issue by BestPig** [JonAbrams/retropatcher#7]
Hello Jon,

I have made some new patches but it seems that Github Actions are not running anymore, so new patches are not grabbed.

Regards,
BestPig

**Comment by JonAbrams** [comment]
The Github Action stopped running due to inactivity. I just reenabled it and it looks like it succeeded. Thanks for the heads up and the patches!

**Comment by JoseJX** [comment]
I'm not sure how often the runner completes, but it looks like it's off again. How often does it need to run to keep it active?  Maybe I can add a game every month or something haha

**Comment by JonAbrams** [comment]
I turned it back on. I can just tell it to not turn off when it emails me
due to inactivity.
